### ISSUE TITLE
SKIP_NULL_FIELDS can lead to inconsistent deserialized data

### ISSUE THREAD

**Issue by rednoah** [jdereg/json-io#101]
Deserializing JSON text serialized with `SKIP_NULL_FIELDS` can lead to inconsistent behaviour when `JsonReader` tries to find an appropriate constructor passing in default values because those default values will not be overridden if the field is not present in the JSON text.

This may or may not be considered a bug but it's definitely strange behaviour, and if it's not considered a bug then this behaviour should be documented in the `SKIP_NULL_FIELDS` documentation.

**Test Case:**

```
import static java.util.Collections.*;

import com.cedarsoftware.util.io.JsonReader;
import com.cedarsoftware.util.io.JsonWriter;

public class NullInteger {

    Integer i;

    public NullInteger(Integer i) {
        this.i = i;
    }

    public static void main(String[] args) throws Exception {
        NullInteger i = new NullInteger(null);

        String json = JsonWriter.objectToJson(i, singletonMap(JsonWriter.SKIP_NULL_FIELDS, true));
        System.out.println(json);

        NullInteger i2 = (NullInteger) JsonReader.jsonToJava(json);
        System.out.println(i.i + " == " + i2.i);
    }

}
```

**Output:**

```
{"@type":"NullInteger"}
null == 0
```

**Workaround:**
Give `JsonReader` a default constructor so it doesn't call the `NullInteger(Integer)` constructor with `0` as argument.

```
public NullInteger() {

}
```

**Comment by jdereg** [comment]
I am not sure I understand your comment 'Give JsonReader a default constructor ...'

The constructor that is needed, in your example, is public NullInteger() { }.  How would JsonReader() create this constructor?  If the code does not have a default constructor, then no default constructor exists for that class.  That is one of the major difficulties in Java, is that there is no 'malloc()' like there is in the C language.

If you have an example of how to foist this default constructor onto other peoples code, please send an example.  The only way I can imagine is to use defineClass() and such other techniques, but then dynamically adding source and compiling it during parsing leads to class loading issues.

**Comment by rednoah** [comment]
The problem stems from `json-io` passing in `0` instead of `null` for `Integer` parameters which caused strange serialize/deserialize issues because `null` fields changed to `0`. 

Without `SKIP_NULL_FIELDS` this is not an issue because `json-io` would just override the `0` passed in the constructor with `null` as it should be.

I think the "correct" behaviour would be to pass `0` as default for `int` parameters but `null` as default for `Integer` parameters.

**Comment by jdereg** [comment]
addressing this next, now that 4.9.0 is out.

**Comment by rednoah** [comment]
Thanks! Much appreciated.

**Comment by jdereg** [comment]
JavaDoc has been updated to note the fact that primitive wrappers will be constructed with their '0' value.
