### ISSUE TITLE
JsonWriter.ENUM_PUBLIC_ONLY doesn't work with custom enums?

### ISSUE THREAD

**Issue by darmbrust** [jdereg/json-io#113]
I'm trying to write out enums in a simple way, with a setup like this:

		DateFormat dateformat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss'Z'", Locale.US);
		dateformat.setTimeZone(TimeZone.getTimeZone("UTC"));
		HashMap<String, Object> config = new HashMap<>();
		config.put(JsonWriter.DATE_FORMAT, dateformat);
		config.put(JsonWriter.SKIP_NULL_FIELDS, true);
		config.put(JsonWriter.TYPE, false);
		config.put(JsonWriter.ENUM_PUBLIC_ONLY, true);
		return JsonWriter.objectToJson(o, config);

But my enums continue to be written out as:
"federationStrategy":{"name":"FEDERATE_THIS","ordinal":1}

I've tried this with both a stand alone class such as:

`public enum FederationStrategy
{
	EXCLUDE, FEDERATE_THIS, FEDERATE_ORIGIN;

	public static FederationStrategy fromName(String name)
	{
		for (FederationStrategy type : values())
		{
			if (type.name().equalsIgnoreCase(name))
			{
				return type;
			}
		}
		return FEDERATE_THIS;
	}

	public boolean exceeds(FederationStrategy type)
	{
		return this.ordinal() > type.ordinal();
	}

	public boolean atLeast(FederationStrategy type)
	{
		return this.ordinal() >= type.ordinal();
	}

	@Override
	public String toString()
	{
		return name();
	}
}`

But also, with the enum FederationStrategy as an enum embedded in another class.

Is there some other trick / gotcha to making the ENUM_PUBLIC_ONLY flag work as expected?

**Comment by darmbrust** [comment]
I did notice that the JsonWriter class calls this method in Class:

    /**
     * Returns true if and only if this class was declared as an enum in the
     * source code.
     *
     * @return true if and only if this class was declared as an enum in the
     *     source code
     * @since 1.5
     */
    public boolean isEnum() {
        // An enum must both directly extend java.lang.Enum and have
        // the ENUM bit set; classes for specialized enum constants
        // don't do the former.
        return (this.getModifiers() & ENUM) != 0 &&
        this.getSuperclass() == java.lang.Enum.class;
    }

Is the comment about specialized enum constants what is hurting us here?

**Comment by jdereg** [comment]
looking into this

**Comment by jdereg** [comment]
Confirming your suspicion, from StackOverflow: http://stackoverflow.com/questions/4166488/checking-if-a-class-is-java-lang-enum

**Comment by jdereg** [comment]
This has been fixed and json-io 4.9.6 released containing the fix.

**Comment by darmbrust** [comment]
Awesome!  Everything else about your project works so well, I just assumed I was doing something dumb for a while :)
