### ISSUE TITLE
deserialization errors (when ref needed by compareTo not yet resolved?)

### ISSUE THREAD

**Issue by rvsasseen** [jdereg/json-io#114]
Hi, I get two different deserialization errors (using the latest version 4.9.6) from the following code, depending on whether the Seq class has a no-arg ctor defined or not. The error when that ctor is defined is probably (I'm guessing) due to a "@ref" in the Seq object not being resolved before the Seq object is placed in a TreeBag, causing its compareTo method to be called while that "@ref" is null, resulting in a NullPointerException. The error when that ctor is not defined is different; less clear what's going on there. Thanks for your attention.

import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.nio.charset.StandardCharsets;
import java.util.HashSet;
import java.util.LinkedHashSet;
import org.apache.commons.collections4.bag.TreeBag;
import org.junit.Test;

import com.cedarsoftware.util.io.JsonReader;
import com.cedarsoftware.util.io.JsonWriter;

public class SerializerTest {

    // This is what fails to deserialize.
    static class TestClass {
        HashSet<Seq> abbrevs  = new LinkedHashSet<>();
        TreeBag<Seq> counts = new TreeBag<>();
    }
    
    // Similar to Java's CharSequence.
    static class Seq implements Comparable<Seq> {
        char[] data;
        int start;
        int end;

        // Fails differently depending on whether or not this is defined.
        public Seq() {
        }
        
        public Seq(String source) {
            data = source.toCharArray();
            start = 0;
            end = source.length();
        }
        
        // "data" is shared rather than copied
        private Seq(char[] data, int start, int end) {
            this.data = data;
            this.start = start;
            this.end = end;
        }

        public Seq subSequence(int start, int end) {
            return new Seq(data, this.start + start, this.start + end);
        }

        public char charAt(int index) {
            return data[index + start];
        }

        public int length() {
            return end - start;
        }
        
        @Override
        public int compareTo(Seq other) {
            int len1 = length();
            int len2 = other.length();
            int lim = Math.min(len1, len2);
            int k = 0;
            while (k < lim) {
                char c1 = charAt(k);
                char c2 = other.charAt(k);
                if (c1 != c2) {
                    return c1 - c2;
                }
                k++;
            }
            return len1 - len2;
        }

        @Override
        public boolean equals(Object obj) {
            if (obj instanceof Seq) {
                Seq obj2 = (Seq) obj;
                if (obj2.length() == length()) {
                    for (int i = 0; i < length(); i++) {
                        if (charAt(i) != obj2.charAt(i)) {
                            return false;
                        }
                    }
                    return true;
                } else {
                    return false;
                }
            } else {
                return false;
            }
        }

        // This is the exact same algorithm as documented for String.
        @Override
        public int hashCode() {
            int length = length();
            if (length == 0) {
                return 0;
            } else {
                int h = 0;
                for (int i = 0; i < length; i++) {
                    h = (31 * h) + charAt(i);
                }
                return h;
            }
        }
    }

    static class Serializer {
        public void store(Object data, OutputStream ostream) {
            try (JsonWriter jw = new JsonWriter(ostream)) {
                jw.write(data);
            }
        }
        public Object load(InputStream istream) {
            try (JsonReader jr = new JsonReader(istream)) {
                return jr.readObject();
            }
        }
    }
        
    @Test
    public void testPossibleBug2() {
        Seq seq1 = new Seq(".vs.");
        Seq seq2 = seq1.subSequence(0, 3);
        TestClass testObject = new TestClass();
        testObject.abbrevs.add(seq1);
        testObject.counts.add(seq2);
        
        Serializer serializer = new Serializer();
        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        serializer.store(testObject, baos);
        byte[] bytes = baos.toByteArray();
        String s = new String(bytes, StandardCharsets.UTF_8);
        System.out.println(s);
        ByteArrayInputStream bais = new ByteArrayInputStream(bytes);
        // Fails inside serializer.load.
        @SuppressWarnings("unchecked")
        TestClass loaded = (TestClass) serializer.load(bais);
    }

}

**Comment by rvsasseen** [comment]
Below is the error output with the ctor defined. (Sorry, in the code I posted above I edited the code for simplicity to call the test class SerializerTest while below it's called com.sri.jminer.utils.UtilJsonSerializer2Test, and the line numbers below from that file are off by +2 because I deleted the package declaration from the posted code.)

Running com.sri.jminer.utils.UtilJsonSerializer2Test
{"@type":"com.sri.jminer.utils.UtilJsonSerializer2Test$TestClass","abbrevs":{"@type":"java.util.LinkedHashSet","@items":[{"@type":"com.sri.jminer.utils.UtilJsonSerializer2Test$Seq","data":{"@id":1,"@items":[".vs."]},"start":0,"end":4}]},"counts":[{"@type":"com.sri.jminer.utils.UtilJsonSerializer2Test$Seq","data":{"@ref":1},"start":0,"end":3}]}
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.041 sec <<< FAILURE! - in com.sri.jminer.utils.UtilJsonSerializer2Test
testPossibleBug2(com.sri.jminer.utils.UtilJsonSerializer2Test)  Time elapsed: 0.04 sec  <<< ERROR!
com.cedarsoftware.util.io.JsonIoException: null
Last read: a.util.LinkedHashSet","@items":[{"@type":"com.sri.jminer.utils.UtilJsonSerializer2Test$Seq","data":{"@id":1,"@items":[".vs."]},"start":0,"end":4}]},"counts":[{"@type":"com.sri.jminer.utils.UtilJsonSerializer2Test$Seq","data":{"@ref":1},"start":0,"end":3}]}
line: 345, col: 345
	at com.sri.jminer.utils.UtilJsonSerializer2Test$Seq.charAt(UtilJsonSerializer2Test.java:53)
	at com.sri.jminer.utils.UtilJsonSerializer2Test$Seq.compareTo(UtilJsonSerializer2Test.java:67)
	at com.sri.jminer.utils.UtilJsonSerializer2Test$Seq.compareTo(UtilJsonSerializer2Test.java:26)
	at java.util.TreeMap.compare(TreeMap.java:1294)
	at java.util.TreeMap.put(TreeMap.java:538)
	at org.apache.commons.collections4.bag.AbstractMapBag.add(AbstractMapBag.java:268)
	at org.apache.commons.collections4.bag.AbstractMapBag.add(AbstractMapBag.java:251)
	at org.apache.commons.collections4.bag.TreeBag.add(TreeBag.java:95)
	at com.cedarsoftware.util.io.ObjectResolver.traverseCollection(ObjectResolver.java:333)
	at com.cedarsoftware.util.io.Resolver.convertMapsToObjects(Resolver.java:138)
	at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:725)
	at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:672)
	at com.sri.jminer.utils.UtilJsonSerializer2Test$Serializer.load(UtilJsonSerializer2Test.java:120)
	at com.sri.jminer.utils.UtilJsonSerializer2Test.testPossibleBug2(UtilJsonSerializer2Test.java:143)

**Comment by jdereg** [comment]
I will take a look.

**Comment by jdereg** [comment]
This is actually not a bug in json-io.  The fix for the issue you are seeing is to make your compareTo() method more robust:
`
       public int compareTo(Seq other)
        {
            if (other.data == null || data == null)
            {
                if (data == other.data)
                {
                    return 0;
                }
                return data == null ? -1 : 1;
            }
            int len1 = length();
            int len2 = other.length();
            int lim = Math.min(len1, len2);
            int k = 0;
            while (k < lim)
            {
                char c1 = charAt(k);
                char c2 = other.charAt(k);
                if (c1 != c2)
                {
                    return c1 - c2;
                }
                k++;
            }
            return len1 - len2;
        }
`

This handles the potentially uninitialized item being passed to the compareTo() and returning a consistent result.  The item that is null is considered 'lesser'.

Another way to handle this is to use your own instantiator for this class.  Associate your instantiator to the Seq.class and make sure the Seq class is initialized in a way that it can handle the compareTo().

I think making the compareTo() method more robust is the best solution.

**Comment by rvsasseen** [comment]
I am concerned that the approaches you suggest may not be sufficient, that they will leave the TreeBag in an inconsistent (improperly ordered) state. (I haven't learned about using an instantiator yet, but I have the same concern there.) 

I half suspect that the approach of first building up a graph with incompletely constructed objects (ones with unresolved @refs) and later patching the graph may have fundamental limitations (despite demonstrated wide applicability), and that the only fully general approach is to first instantiate the objects and then assemble the graph -- but I'm not at all sure of that, especially since you probably can't do that when you have circular references.

Unfortunately I can't take time to look further into this right now, because json-io is just our debugging serialization while kryo is our production serialization. But I wanted to report the original problem and follow up with this comment to help improve the library, which we have found very useful.

Also, did you try running the test with the Seq no-arg constructor commented out? The exception that occurs in that case is different, and it occurs in json-io code, not in the Seq or TestClass code.
