### ISSUE TITLE
Missing field handler does not support complex types

### ISSUE THREAD

**Issue by sgandon** [jdereg/json-io#115]
The current implementation of the migration callback for missing field handling only handles primitive type and not complex types.
I'll provide a PR that improves this a little bit when the type of the missing field can be found in the json using the @type.

**Comment by jdereg** [comment]
I'ved merge the PR.  Plan to look it over, test it a bit.  Should be able to release a 4.9.8 by the weekend.

**Comment by jdereg** [comment]
Version 4.9.8 has been released with your changes.
