### ISSUE TITLE
Map<String, Object> typed serialization broken for Integer and Date objects

### ISSUE THREAD

**Issue by costin3141** [jdereg/json-io#119]
I have the following example code:

-----------------------------------------------------
public static void main( String[] args ) {
      final Map<String, Object> map = new HashMap<>();
      map.put( "Long", Long.valueOf( 179 ) );
      map.put( "Integer", Integer.valueOf( 179 ) );
      map.put( "Double", Double.valueOf( 179 ) );
      map.put( "date", new Date() );
      
      final Map params = new HashMap();
      params.put(  JsonWriter.DATE_FORMAT, JsonWriter.ISO_DATE_TIME_FORMAT );
      
      final String str = JsonWriter.objectToJson( map, params );
      System.out.println( str + "\n" );
      
      final Map<String, Object> map2 = JsonReader.jsonToMaps( str );
      
      for( Entry<String, Object> entry : map2.entrySet() ) {
         System.out.println( entry.getKey() + " : " + entry.getValue() + " | " + entry.getValue().getClass().getSimpleName() );
      }
   }
----------------------------------------

which produces the following:

{"@type":"java.util.HashMap","Integer":{"@type":"int","value":179},"date":{"@type":"date","value":"2017-08-16T12:23:18"},"Long":179,"Double":179.0}

Integer : {value=179} | JsonObject
date : {value=2017-08-16T12:23:18} | JsonObject
Long : 179 | Long
Double : 179.0 | Double

As you can see it fails deserializing the Integer object and the Date object. Interesting is that on serialization exactly these two objects have a different style of type information as the other objects. While Long object got type "Long" the Date object got "date" and Integer got "int".

Something seems broken here.

**Comment by costin3141** [comment]
Damn, that formatting here is also broken :(

**Comment by jdereg** [comment]
I will look into this, build tests, fix, and re-release. May take a few days.

**Comment by jdereg** [comment]
This has been fixed, test added, and released in 4.10.0.

**Comment by gunmiosb** [comment]
Problem seems to still be there. In JsonWriter.writeCollectionElement() only boolean, double and long are written as primitives. Int uses writeImpl and converts it to an object.
`	public static void main(String[] args) {
		HashMap<String,Object> map = new HashMap<>();
		map.put("int", 1);
		map.put("long", 2l);
		String json = JsonWriter.objectToJson(map);
		System.out.println(json);
	}`
Results in:
{"@type":"java.util.HashMap","int":{"@type":"int","value":1},"long":2}
