### ISSUE TITLE
SKIP_NULL_FIELDS collections

### ISSUE THREAD

**Issue by nnar1o** [jdereg/json-io#125]
Collection fields that contain no elements are not omitted. Is there any option to skip such fields? If not so please add feature.

**Comment by jdereg** [comment]
There is a difference between a field pointing to an empty collection versus a field that has a value of null that could end up holding a collection.

Basically,
1. items = null
2. items = [ ]  // empty collection
3. items = [a, b, ... ] . // collection of items

Item 2 is semantically different than item 1.  json-io is just honoring the source graph.
