### ISSUE TITLE
How to add this library as gradle dependency for Android Studio?

### ISSUE THREAD

**Issue by ozmium** [jdereg/json-io#126]
How do we include this library dependency in an Android gradle project? (without downloading the jar file)

This doesn't work with gradle 4.1:

**build.gradle:**
```javascript
allprojects {
    repositories {
        jcenter()
        mavenCentral() // New item added - It does not resolve dependency error
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }
}
```

**app/build.gradle:**
```javascript
dependencies {
    compile 'com.cedarsoftware:json-io:4.10.0' // Error: "Unable to resolve dependency..."
}
```

**Comment by jdereg** [comment]
I will be looking into this.  My plan is to convert my opensource projects from Maven to Gradle.  At that point, I will better understand how to answer / deal with this request.

**Comment by ozmium** [comment]
This seems to be fixed now:

https://search.maven.org/artifact/com.cedarsoftware/json-io/4.10.1/bundle

```javascript
dependencies {
    implementation 'com.cedarsoftware:json-io:4.10.1'
}
```

**Comment by Agonizedcupid** [comment]
HttpResponse<JsonNode> jsonResponse = Unirest.post("http://httpbin.org/post")
                .header("accept", "application/json")
                .field("parameter", "value")
                .field("file", new File("/tmp/file"))
                .asJson();

here asJson() method unable to resolve . how can i use asJson() method
