### ISSUE TITLE
How to handle restore of renamed classes, in newer code version?

### ISSUE THREAD

**Issue by ozmium** [jdereg/json-io#127]
Suppose that you already have some stored JSON state on disk for a class `"Employee"`. Then you rename the class in a newer version of your code, to `"EmployeeRenamed"`. Then you try to restore the state of the renamed class. This will cause a class cast Exception in json-io, as shown here:

```java
@Test
public void testJsonSaveAndRestoreOfRenamedClass() {

    class Employee {
        String name = "Alexis";
        int age = 34;
    }

    class EmployeeRenamed {
        String name;
        int age;
    }

    Employee employee = new Employee();
    String json = JsonWriter.objectToJson(employee);
    System.out.println("object to json = " + json);

    // java.lang.ClassCastException will happen here ("Employee cannot be cast to EmployeRenamed") 
    EmployeeRenamed employeeRenamed = (EmployeeRenamed) JsonReader.jsonToJava(json);
    System.out.println("Restored employee age = " + employeeRenamed.age);
    System.out.println("Restored employee name = " + employeeRenamed.name);

    assertThat(employee.name, is(employeeRenamed.name));
    assertThat(employee.age, is(employeeRenamed.age));
}
```

Is there a way to workaround this in json-io, perhaps by forcing the type conversion or changing the stored type?

**Comment by jdereg** [comment]
json-io and other serializers are normally mean to be used to decompose an in-memory object graph to JSON only transiently, not for persistence.  If you are persisting the generated JSON to a document store (for example), then if someone is renaming classes, it should be on that person or team to make sure to update the stored documents as well.
