### ISSUE TITLE
JsonReader.jsonToJava() should accept null or empty String, to return null

### ISSUE THREAD

**Issue by ozmium** [jdereg/json-io#129]
Currently, this code causes an exception in the json-io library:

    Object object1 = JsonReader.jsonToJava("");
    Object object2 = JsonReader.jsonToJava(null);

Please make the JsonReader return `null` objects in these scenarios. Otherwise the caller has to write extra code to deal with null and empty strings. It would be better if the library handled it, and it would also make the library easier to use.

**Comment by jdereg** [comment]
Good suggestion.  Many upcoming changes planned. Will be add.

**Comment by jdereg** [comment]
Implemented in 4.11.0
