### ISSUE TITLE
Some source code suggestions

### ISSUE THREAD

**Issue by ericktang** [jdereg/json-io#132]
Source code have many const String like: "@id","@keys","@items","@type",etc., may be use some final static String to define them is a good purpose.

**Comment by ericktang** [comment]
**next code may be an error.**
```
private void writeArray(final Object array, boolean showType) throws IOException
    {
........
 if (typeWritten || referenced)
        {
            output.write(shortMetaKeys ? "\"@i\":[" : "\"@items\":[");
        }
....
}
```

**Comment by jdereg** [comment]
This has been fixed and test added.  Will be publishing new json-io version within a day or so.  I am looking through other issues to possibly include in this next release.
