### ISSUE TITLE
Double quote character (char 34) reads as \u0000

### ISSUE THREAD

**Issue by EugeneImbro** [jdereg/json-io#135]
I tried to parse following JSON Object:

`{
  "@type": "char",
  "value": "\""
}`

    @Test
    public void justTest() {
        String jsonString = "{\"@type\":\"char\",\"value\":\"\\\"\"}";
        JsonReader jsonReader = new JsonReader(new ByteArrayInputStream(jsonString.getBytes(Charsets.UTF_8)));
        Object object = jsonReader.readObject();
        assertThat((Character) object).isEqualTo('"');
    }

'"' deserializes as '\u0000'

**Comment by jdereg** [comment]
This has been fixed.  It will be released in 4.11.0
