### ISSUE TITLE
json-io not working on Android 10

### ISSUE THREAD

**Issue by enderk** [jdereg/json-io#141]
Regarding to Android docs (https://developer.android.com/about/versions/10/non-sdk-q) now value fields removed so reflection based mapping for primitives not working. 

Ljava/lang/Boolean;->value:Z   # java.lang.Boolean.booleanValue()
Ljava/lang/Byte;->value:B   # java.lang.Byte.byteValue()
Ljava/lang/Character;->value:C   # java.lang.Character.charValue()
Ljava/lang/Double;->value:D   # java.lang.Double.doubleValue()
Ljava/lang/Float;->value:F   # java.lang.Float.floatValue()
Ljava/lang/Integer;->value:I   # java.lang.Integer.intValue()
Ljava/lang/Long;->value:J   # java.lang.Long.longValue()
Ljava/lang/Short;->value:S   # java.lang.Short.shortValue()

Workoround: can provide custom serializer for primitive types.

**Comment by ozmium** [comment]
Yes this is a big problem. Oddly, some auto-boxed primitives work (like `Long`), and others do not (like `Integer`). Examples:

**Run this on an Android 10 or 11 device:**

```java
ArrayList<Long> arrayList = new ArrayList<>(Arrays.asList(10L, 20L, 30L, 40L));
String serializedArrayList = JsonWriter.objectToJson(arrayList);
System.out.println("serializedArrayList = " + serializedArrayList); // prints {"@type":"java.util.ArrayList","@items":[10,20,30,40]}

ArrayList<Integer> arrayListInts = new ArrayList<>(Arrays.asList(10, 20));
serializedArrayList = JsonWriter.objectToJson(arrayListInts);
System.out.println("serializedArrayList = " + serializedArrayList); // prints {"@type":"java.util.ArrayList","@items":[{"@type":"int"},{"@type":"int"}]}
```

------

As an unrelated point, I noticed that the JsonWriter constructor has duplicate lines to read the property `WRITE_LONGS_AS_STRINGS`:

https://github.com/jdereg/json-io/blob/31a5c7961c050f7abc6d08011d7e69a1555d4e99/src/main/java/com/cedarsoftware/util/io/JsonWriter.java#L393:L394

```java
public JsonWriter(OutputStream out, Map<String, Object> optionalArgs)
{
    ...
    writeLongsAsStrings = isTrue(args.get(WRITE_LONGS_AS_STRINGS));
    writeLongsAsStrings = isTrue(args.get(WRITE_LONGS_AS_STRINGS));
    ...
}
```

**Comment by jdereg** [comment]
json-io has been updated to only access fields direclty if it has permission to do so.  If not, the ReadOptionsBuilder and WriteOptionsBuilder allow directing access via methods and method patterns you configure.
