### ISSUE TITLE
Illegal reflective access

### ISSUE THREAD

**Issue by ghost** [jdereg/json-io#143]
Hello,

Ive warning with latest json-io and jdk 11 : 

`jvm 1    | WARNING: An illegal reflective access operation has occurred
jvm 1    | WARNING: Illegal reflective access by com.cedarsoftware.util.io.MetaUtils (file:/C:/Users/Administrator/Documents/GitHub/xxx/lib/json-io-4.11.1.jar) to field java.lang.Integer.value
jvm 1    | WARNING: Please consider reporting this to the maintainers of com.cedarsoftware.util.io.MetaUtils
jvm 1    | WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
jvm 1    | WARNING: All illegal access operations will be denied in a future release`

Can you fix it?

Thx!

**Comment by jdereg** [comment]
These has been corrected and made compatible for JDK11 through JDK21
