### ISSUE TITLE
UnmodifiableMap can not be deserialized

### ISSUE THREAD

**Issue by reuschling** [jdereg/json-io#16]
JsonReader performs a method 'rehashMaps()' that invokes 'map.put(..)' which leads to an UnsupportedOperationException
Here is an example code:
```java
   HashMap<String, String> hsOurMap = new HashMap<>();
   hsOurMap.put("key", "val");

   String strJson = JsonWriter.objectToJson(Collections.unmodifiableMap(hsOurMap));
   HashMap<String, String> clone = (HashMap<String, String>) JsonReader.jsonToJava(strJson);
```

**Comment by jdereg** [comment]
Support for serializing unmodifiable Collections and Maps has been implemented in 2.9.0.
