### ISSUE TITLE
Release 4.14.1 to close CVE issue

### ISSUE THREAD

**Issue by anthonydahanne** [jdereg/json-io#174]
Hello,
As mentioned here https://github.com/jdereg/json-io/issues/169#issuecomment-1690025620 , could you please cut a new release to get rid of the CVE mentioned at: https://github.com/advisories/GHSA-779h-3r69-4f5p

Thank you in advance!!!

**Comment by anthonydahanne** [comment]
@jdereg any updates? thank you!

**Comment by jdereg** [comment]
releasing now...
