### ISSUE TITLE
Possible issue about list of objects that have custom writers

### ISSUE THREAD

**Issue by williamclocksin** [jdereg/json-io#199]
I am using json-io to serialise object graphs that have a lot of circular references, some custom readers/writers, and blacklisting. I have only one unresolved issue. I am trying to serialise an object in which one field is an ArrayList of other objects that have custom writers. When they are in the ArrayList, the custom writers don't seem to be called. The default (non custom) writer is called. However, when these objects are fields, the custom writer is called as expected. Is the handling of custom writers not being done when the object is in an ArrayList?

**Comment by jdereg** [comment]
What "write" parameters (if any) are you using to write your JSON?

**Comment by williamclocksin** [comment]
Here is the writer:

```
public static class TextBoxWriter implements JsonWriter.JsonClassWriter
  {

    public void write(Object o, boolean showType, Writer output) throws IOException
    {
      TextBox p = (TextBox) o;
      output.write("\"subtype\":");
      output.write(Integer.toString(p.subtype));
      output.write(",\"xoff\":");
      output.write(Double.toString(p.xoff));
      output.write(",\"yoff\":");
      output.write(Double.toString(p.yoff));
      output.write(",\"area\":");
      output.write(Serialising.toString(p.area));
    }


    public boolean hasPrimitiveForm() { return false; }

    public void writePrimitiveForm(Object o, Writer output) throws IOException
    {
      write(o, true, output);
    }
  }

```
The `area` is a RichTextFX box, and I have my own function to convert it into a styled string that is serialised, instead of attempting to serialise a JavaFX Node.  TextBoxWriter is mapped with
 arg.put(jsonio.JsonWriter.CUSTOM_WRITER_MAP, Serialising.getCustomWriters());
where Serialising.getCustomWriters() returns my Map of custom writers.
This all works when the TextBox is serialised by itself.  But when it is an element of an ArrayList which is then serialised, the custom writer is not used, and the JSON gets the serialised Node in all its unwanted verbosity and structure.

**Comment by williamclocksin** [comment]
Here is the start of class TextBox, showing the fields to serialise.  None are blacklisted.

```
public class TextBox extends Hanger
{

  int subtype;
  double xoff, yoff;
  InlineCssTextArea area;
...

```
And here is a correctly serialised TextBox with the unstyled text "text":

{"@type":"calliope.TextBox","subtype":7,"xoff":302.0,"yoff":286.0,"area":#!pcr!#text#!scr!##!seg!##!par!#}

But when a TextBox is included in an ArrayList, it serialises the whole InlineCssTextArea, which is not wanted.

**Comment by jdereg** [comment]
This issue has been fixed.  It is fixed in the origin/master, and will be in the upcoming 4.14.3 release.  This release will also add back JDK1.8 (thru JDK21 support).

**Comment by williamclocksin** [comment]
Thank you! You're a star.
