### ISSUE TITLE
Compile / runtime dependency on com.novell.ldap:jldap

### ISSUE THREAD

**Issue by aukevanleeuwen** [jdereg/json-io#250]
For some reason in this commit https://github.com/jdereg/json-io/commit/dacf7093b254812abb75a6ea1deb88c71b9635d2 a new dependency was introduced:

```xml
        <!-- https://mvnrepository.com/artifact/com.novell.ldap/jldap -->
        <dependency>
            <groupId>com.novell.ldap</groupId>
            <artifactId>jldap</artifactId>
            <version>2009-10-07</version>
        </dependency>
```

For a library that explicitly states that it has no dependencies, this seems a bit odd:

https://github.com/jdereg/json-io/blob/0e99ae9c8a327be461664ed0247ae547b5288874/README.md#L9

Also: I have no idea how JSON I/O and LDAP have anything to do with each other, so maybe this was just a mistake? It would be great it it could be removed, because I'm getting flagged with licensing issues on the LDAP library.

**Comment by jdereg** [comment]
I believe that dependency was inadvertently added when a reported issue was being debugged.  Anyway, it's removed, json-io will continue moving forward with "no dependencies" mantra.

**Comment by aukevanleeuwen** [comment]
Thanks. Question: I see main branch is on 5.0.0-SNAPSHOT, are you planning on backporting to 4.x?

**Comment by jdereg** [comment]
We are continuing on the 4.x path, with 4.20.0 next.  Staying with Java 1.8+ compatibility and no dependencies :-). The plan is for 5.x to be where we move up to Java 17 - not set in stone.  The main "API" is the static methods on JsonIo and the ReadOptions and WriteOptions.  For generic non-Java returns, JsonObject will continue to be used.
