### ISSUE TITLE
User guide Untyped Usage

### ISSUE THREAD

**Issue by Amosnomor** [jdereg/json-io#282]
The user guide section for untyped usage  says:
```
    String json = // or InputStream to JSON providing source
    ReadOptions readOptions = new ReadOptionsBuilder().returnAsNativeJsonObjects().build();
    Map root = JsonIo.toObjects(json, readOptions);  
```
But JsonIo.toObjects() currently requires a third parameter, rootType.  Looking at the TestUtil.java shows it passing null for this case:
```
    public static JsonObject toObjects(InputStream in, ReadOptions readOptions) {
        return JsonIo.toObjects(in, readOptions, null);
    }
```
Should there be another signature without the rootType parameter?  Or will passing null need to be documented?  Or?

**Comment by jdereg** [comment]
Good catch.  Passing in null is documented in the JavaDocs, however, I will add a root class to the example.
