### ISSUE TITLE
high usage of metaspace after upgrade to 4.22.0

### ISSUE THREAD

**Issue by andre-pt** [jdereg/json-io#283]
Hi,

we had an application for some years working with 4.14.0 and today we rolled out an update to 4.22.0.

We noticed instances getting `java.lang.OutOfMemoryError: Metaspace` and started investigating.

Metaspace usage was constant before this update and now we had to increase it to avoid running into OutOfMemory:
![image](https://github.com/jdereg/json-io/assets/8385067/f2184b75-d340-4cd6-bd60-a4a99147cc60)

We also noticed that loaded classes increased significantly:
![image](https://github.com/jdereg/json-io/assets/8385067/f4ff6a61-9482-464f-8f98-140106c4c24f)

We are using the following 2 methods:
```
    public static String toJson(Object o) {
        return JsonIo.toJson(o, null);
    }

    public static <T> T toObject(String json, Class<T> rootType) {
        return JsonIo.toObjects(json, null, rootType);
    }
```

Is this behavior expected? 
Is there anything we can do to limit the usage of metaspace?

Thanks a lot
Andre

**Comment by andre-pt** [comment]
my previous solution resolved the metaspace usage issue.

**Comment by jdereg** [comment]
Andre, thank you for posting the journey you made.  You are absolutely correct in your conclusion, that the intention is that we expect a ReadOptions instance and a WriteOptions instance should be created and held onto.  I will make sure our documentation is more clear on that.  Thank you again for your posts.
