### ISSUE TITLE
Final fields can't be set by a new version of library

### ISSUE THREAD

**Issue by ozhelezniak-talend** [jdereg/json-io#287]
Because a new version is using MethodHandles.unreflectSetter and it can't be used for final fields.
A previous version (around 4.14.0) was able to do that. Frankly, didn't get how it ignored the restriction.

Right now, I don't see a good extension point to remove the final modifier from the field with reflection before the looking for unreflectSetter method. 
Only the extending with reflection the list of "fieldFilters" with a custom filter, that instead of filtering modifies the field modifiers with reflection. 
It looks very dirty. 

Does anyone know a better solution?

Also, I'm wondering why we can't declare a custom com.cedarsoftware.io.reflect.InjectorFactory? I suppose it may resolve the issue.

**Comment by jdereg** [comment]
Your ReadOptions.addInjectorFactory() PR has been merged.

**Comment by jdereg** [comment]
Fixed by PR from @ozhelezniak-talend
