### ISSUE TITLE
java.lang.VerifyError with 2.9.2 and Android < 5.0

### ISSUE THREAD

**Issue by Farasy** [jdereg/json-io#36]
I downloaded the 2.9.2 library to support Android > 5.0. It works well, but on devices lower 5 the following error is thrown:

02-09 14:20:22.210: E/AndroidRuntime(18869): java.lang.VerifyError: com/cedarsoftware/util/io/JsonReader
02-09 14:20:22.210: E/AndroidRuntime(18869): 	at com.cedarsoftware.util.io.JsonWriter.traceReferences(JsonWriter.java:791)
02-09 14:20:22.210: E/AndroidRuntime(18869): 	at com.cedarsoftware.util.io.JsonWriter.write(JsonWriter.java:759)
02-09 14:20:22.210: E/AndroidRuntime(18869): 	at com.cedarsoftware.util.io.JsonWriter.objectToJson(JsonWriter.java:209)
02-09 14:20:22.210: E/AndroidRuntime(18869): 	at com.cedarsoftware.util.io.JsonWriter.objectToJson(JsonWriter.java:163)

**Comment by jdereg** [comment]
What JDK are these earlier devices using?  json-io requires JDK 1.7.

**Comment by Farasy** [comment]
Thanks for your fast response. I guess it uses 1.6. :/
