### ISSUE TITLE
Class file not compatible with older versions of Java

### ISSUE THREAD

**Issue by SlimerDude** [jdereg/json-io#38]
Assuming the lib doesn't use any newer Java features, could the source be recompiled so it's compatible with older versions of Java?

Being a JDK 1.6 user I currently get:

    Unsupported major.minor version 51.0

This [SO question](http://stackoverflow.com/questions/10382929/how-to-fix-unsupported-major-minor-version-51-0-error) explains a bit more if you're unsure.

I know I can do it myself, but it's always nice not having to build from source.

**Comment by jdereg** [comment]
I believe there are uses of the 'diamond operator' used that may stop the
source from being compiled:

    List<String> names = new ArrayList<>()

I have no problem with you forking the json-io repo, and modifying the
source there to be JDK 1.6 compliant.  Then feel free to share the link to
your repo as the 1.6 json-io.  I'd hope that you would keep it up-to-date
with changes to the Cedar Software json-io.  I don't plan to move to JDK
1.8 until 1.7 is sunsetted.  Even then, I will try to hold off.  Lambda
functions would be the main enticement to move to JDK 1.8.

**Comment by SlimerDude** [comment]
Generics were introduced in Java 1.5, so _diamond operators_ shouldn't be a problem.

To produce backwards compatible class files shouldn't take much more than setting the `target` option in the compiler. Here's a link on how to set it in the [Maven .pom file](http://maven.apache.org/plugins/maven-compiler-plugin/examples/set-compiler-source-and-target.html).

**Comment by jdereg** [comment]
The diamond operator (on the RHS) support was not added (as I understand
it) until Java 1.7.  Please try it and see if you can compile the example
line I sent.

**Comment by SlimerDude** [comment]
With regards to the line:

    List<String> names = new ArrayList<>()

while the syntax is Java 1.7, the JDK can still compile it to Java 1.5 / 1.6 compatible byte code resulting in a class file usable by all (the purpose of the said `target` compiler option).

But on further inspection of the source code, I see you're using `java.lang.ReflectiveOperationException` in `MetaUtils` which was only introduced in Java 1.7 - so obviously those references won't resolve in earlier JDKs.

Oh well - I was only after a quick one-liner for pretty printing JSON. Hope you don't mind but I've gone with the usual GSON...
