### ISSUE TITLE
Possible to omit "@type" property when writing?

### ISSUE THREAD

**Issue by alexgaribay** [jdereg/json-io#41]
Is it possible to omit the "@type" property when writing? I didn't find in the documentation whether it is possible but it doesn't state why the property is there. My use case doesn't need it since I don't convert my data back to Java objects.

**Comment by jdereg** [comment]
I am pondering this suggestion.  Normally, json-io always writes JSON that can be reconstituted back into Java objects.  If the @types were removed, then you would be creating JSON that would not be reconstitutable back into Java.  However, it could be read into Maps (JsonObjects) and still read from.

If it is added, it will be a new flag to be indicated in the options Map passed into the JsonWriter.

**Comment by jdereg** [comment]
This enhancement has been implemented.  Setting the JsonWriter.TYPE = false in the 'optional args' will tell json-io not to output any @type entries.  Please note that the resulting JSON will likely not be able to re-constituted as Java objects (pure Java serialization).
