### ISSUE TITLE
feature request: allow to define  max-depth for an object graph

### ISSUE THREAD

**Issue by donshop11** [jdereg/json-io#46]
it is sometimes useful, when the object graph is very big, to define  maximum depth for the traversal.
is it possible to do today?

**Comment by jdereg** [comment]
Although it is not possible to define maximum depth, I am not sure I would want that.  If it stopped writing or reading at a certain depth, the resulting graph would be incomplete and therefore potentially untrustworthy.

I would like to point out that although the parser uses a stack-based parse, the conversion from Maps to Objects uses an explicit Stack object (limited only by the size of the heap).  Similarly, the writer uses an explicit Stack for tracing the graph to find references (limited only by the size of the heap) but it does uses the Java stack while writing.

On my list of 'TODO's' for json-io, is to convert those final two instances of recursion to also use an explicit stack, thereby all graph traversing is only bound by heap size.  I plan to attack the parser first, and when that is released, any depth based graph will be readable (limited entirely only by heap).  After that is completed, I will do the same for the writer.  This will not happen soon, but it will happen.
