### ISSUE TITLE
Could not instantiate java.net.URL using any constructor during JsonReader.jsonToJava

### ISSUE THREAD

**Issue by mancioshell** [jdereg/json-io#5]
Hi,
I'm trying to serialize/deserialize DataHandler (http://docs.oracle.com/javase/7/docs/api/javax/activation/DataHandler.html) object to json and vice versa, but it occurs an error during the process:

```
{"@type":"javax.activation.DataHandler","dataSource":{"@type":"javax.activation.URLDataSource","url":{"protocol":"http","host":"www.google.com","port":-1,"file":"","authority":"www.google.com","ref":null,"hashCode":-1},"url_conn":null},"objDataSource":null,"object":null,"objectMimeType":null,"currentCommandMap":null,"transferFlavors":[],"dataContentHandler":null,"factoryDCH":null,"oldFactory":null,"shortType":null}
Exception in thread "main" java.io.IOException: IllegalAccessException setting field 'url' on target: javax.activation.URLDataSource@e5590e with value: {protocol=http, host=www.google.com, port=-1, file=, authority=www.google.com, ref=null, hashCode=-1}
Last read: "transferFlavors":[],"dataContentHandler":null,"factoryDCH":null,"oldFactory":null,"shortType":null}
line: 1, col: 419
    at com.cedarsoftware.util.io.JsonReader.error(JsonReader.java:3199)
    at com.cedarsoftware.util.io.JsonReader.assignField(JsonReader.java:1863)
    at com.cedarsoftware.util.io.JsonReader.traverseFields(JsonReader.java:1731)
    at com.cedarsoftware.util.io.JsonReader.convertMapsToObjects(JsonReader.java:1263)
    at com.cedarsoftware.util.io.JsonReader.convertParsedMapsToJava(JsonReader.java:1202)
    at com.cedarsoftware.util.io.JsonReader.readObject(JsonReader.java:1166)
    at com.cedarsoftware.util.io.JsonReader.jsonToJava(JsonReader.java:1084)
    at prova.gson.App.main(App.java:24)
Caused by: java.io.IOException: Could not instantiate java.net.URL using any constructor
Last read: "transferFlavors":[],"dataContentHandler":null,"factoryDCH":null,"oldFactory":null,"shortType":null}
line: 1, col: 419
    at com.cedarsoftware.util.io.JsonReader.error(JsonReader.java:3194)
    at com.cedarsoftware.util.io.JsonReader.tryOtherConstructors(JsonReader.java:2679)
    at com.cedarsoftware.util.io.JsonReader.newInstanceEx(JsonReader.java:2639)
    at com.cedarsoftware.util.io.JsonReader.newInstance(JsonReader.java:2615)
    at com.cedarsoftware.util.io.JsonReader.createJavaObjectInstance(JsonReader.java:2112)
    at com.cedarsoftware.util.io.JsonReader.assignField(JsonReader.java:1838)
    ... 6 more

```

This is my code snippet:

```
package mypackage;

import java.io.IOException;
import java.net.URL;
import javax.activation.DataHandler;
import javax.activation.DataSource;
import com.cedarsoftware.util.io.JsonReader;
import com.cedarsoftware.util.io.JsonWriter;

public class App 
{
    public static void main( String[] args ) throws IOException 
    {               
        DataHandler obj = new DataHandler(new URL("http://www.google.com"));
        String json = JsonWriter.objectToJson(obj);        
        System.out.println(json);        
        Object obj2 = JsonReader.jsonToJava(json);
    }
}
```

**Comment by darabos** [comment]
Have you considered using [Objenesis](http://objenesis.org/)? It is dedicated to the tricky business of instantiating objects. It's great that `json-io` has no dependencies, but I'd rather have one dependency than have to deal with this stuff.

**Comment by jdereg** [comment]
I have considered Objenesis, but it adds an addition 250K dependency and it requires the sun.misc.* package which may not always be available.

Rather than add this dependency for the rare case, json-io provides the ability to associate a factory class to a class that will be called so that you can create the instance:

    /**
     * For difficult to instantiate classes, you can add your own ClassFactory
     * which will be called when the passed in class 'c' is encountered.  Your
     * ClassFactory will be called with newInstance(c) and your factory is expected
     * to return a new instance of 'c'.
     *
     * This API is an 'escape hatch' to allow ANY object to be instantiated by JsonReader
     * and is useful when you encounter a class that JsonReader cannot instantiate using its
     * internal exhausting attempts (trying all constructors, varying arguments to them, etc.)
     */
    public static void assignInstantiator(Class c, ClassFactory f)
    {
        factory.put(c, f);
    }

To use, simply do this:

    JsonReader.assignInstantiator(Qux.class, quxFactory);

This will call the quxFactory `newInstance(class)` method:

    public interface ClassFactory
    {
        Object newInstance(Class c);
    }

The QuxFactory would instantiate Qux instances when called.  It allows json-io to instantiate anything.  If your QuxFactory wants to use objenesis, by all means feel free.  You could write an Objenesis factory that instantiates all calls to this, but even still, json-io has no dependency on the objensis library.

**Comment by darabos** [comment]
Thanks! I like this pluggable approach. I just worry that I will have to add a lot of custom instantiators. I'm working on a Scala system and Scala's standard library is full of weird classes. I had to add a custom instantiator for `scala.collection.immutable.MapLike$ImmutableDefaultKeySet` already. If this turns out to be a problem, a method for setting a new default `ClassFactory` (used for all classes) could be a helpful.

But maybe it's just that one class and I'll be fine otherwise! I've just started using `json-io`, but it looks excellent so far.

**Comment by jdereg** [comment]
Daniel, glad to hear you are getting your arms around the library.  I would
think you should not need too many custom instantiators, as json-io makes a
pretty aggressive attempt at instantiating objects.  It tries the default
constructor if one exists, if not it then tries all constructors (private,
protected, package friendly or public) twice - once with null, 0, "", for
the various arguments, and then it tries them a 2nd time if it none have
yet worked - this time, putting in more reasonable, non-null, non-zero,
no-empty string values.  Once it finds a constructor that works, it caches
it and uses it from there on out through the rest of the serialization
reading process.

As much as json-io goes the extra mile for instantiation, if you find
yourself having to add what you think are too many ClassFactory
instantiators, then you could create a single one, and use objenesis in
that ClassFactory, for all classes that are difficult.

Another note - you can use JsonWriter to 'pretty print' your JSON if needed
for debugging.  It uses the same indent and format as jsoneditoronline.org.
This is useful when dumping objects out when deubgging code - you can dump
entire objects out in println statements, in a nice-readable format.
