### ISSUE TITLE
Error when attempting to serialize an object marked transient

### ISSUE THREAD

**Issue by francisu** [jdereg/json-io#53]
If a transient object cannot be examined and gives an exception it will blow up the serialization. transient objects should not be accessed for serialization.

I will supply a pull request for this.

**Comment by francisu** [comment]
See https://github.com/jdereg/json-io/pull/54

**Comment by jdereg** [comment]
Nice fix for troubling transients.  Your changes have been incorporated and a new version (4.1.7) of json-io has been released to Maven Central.  I would expect it to be available for download within 2 hours of me writing this message.

**Comment by jdereg** [comment]
Francis, check out the code in my final fix.  Transient fields cannot be entirely skipped - if a field specifier map is used for the class, and the transient field is listed, then the transient field must be traced.  It is a slight modification to the code you submitted.  That fix (and a new test to ensure it is working correctly) was released in 4.1.8.

**Comment by francisu** [comment]
Your fix and tests look great. Thanks for such quick turnaround on my PR, and also for being the only game in town for Java -> JSON serialization that supports object graphs with cycles with no fuss.
