### ISSUE TITLE
NaN, Infinity, -Infinity is not supported

### ISSUE THREAD

**Issue by lordvlad** [jdereg/json-io#62]
When objects contain fields with NaN, Infinity or -Infinity, an invalid JSON string is produced.

ex:

    class O {
      double num = Double.NaN;
    }

    JSONWriter.objectToJson( new O() );
    // {"num": NaN}

in contrast v8's implementation turns these into `null`

    JSON.stringify({'num', NaN})
    // {"num": null}

**Comment by jdereg** [comment]
fixed
