### ISSUE TITLE
add an ioption to skip empty (null) object's fields in output json

### ISSUE THREAD

**Issue by rvaleryr** [jdereg/json-io#65]
in many cases java objects have some set of fields with null values. 
(it can be even huge)

the option to do not write such fields will be very useful.

**Comment by rvaleryr** [comment]
// + protected to get ability to override, + boolean omitNulls parameter
protected boolean writeField(Object obj, boolean first, String fieldName, Field field, boolean allowTransient, boolean omitNulls) throws IOException
    {
        if (!allowTransient && (field.getModifiers() & Modifier.TRANSIENT) != 0)
        {   // Do not write transient fields
            return first;
        }

        int modifiers = field.getModifiers();
        if (field.getDeclaringClass().isEnum() && !Modifier.isPublic(modifiers) && isEnumPublicOnly)
        {
            return first;
        }

        if (!first)
        {
            out.write(',');
            newLine();
        }

        Object o;
        try
        {
            o = field.get(obj);
        }
        catch (Exception ignored)
        {
            o = null;
        }

        if (o == null && !omitNulls) // write nulls if omitNulls is false 
        {    
            writeJsonUtf8String(fieldName, out);
            out.write(':');
            // don't quote null
            out.write("null");
            return false;
        }
        
        writeJsonUtf8String(fieldName, out);
        out.write(':');

        Class type = field.getType();
        boolean forceType = o.getClass() != type;     // If types are not exactly the same, write "@type" field

        //When no type is written we can check the Object itself not the declaration
        if (MetaUtils.isPrimitive(type) || (neverShowType && MetaUtils.isPrimitive(o.getClass())))
        {
            writePrimitive(o, false);
        }
        else
        {
            writeImpl(o, forceType || alwaysShowType);
        }
        return false;
    }

**Comment by jdereg** [comment]
Looking into your request.  I believe I can get this implemented quickly.  Perhaps have a release available within 1 week.

**Comment by rvaleryr** [comment]
Hi, it sounds great!
This will be a really excellent feature
--
Отправлено из Mail.Ru для Android воскресенье, 31 января 2016г., 08:43 +03:00 от Cedar Software < notifications@github.com> :

**Comment by jdereg** [comment]
This has been implemented and released in json-io 4.3.1.
