### ISSUE TITLE
JsonObject.getArray VS Object[]

### ISSUE THREAD

**Issue by rednoah** [jdereg/json-io#70]
One of the recent updates changed how JS arrays are parsed. Previously it used to be `JsonObject` instances, but now it's just `Object[]` which so I've got to fix a lot of `ClassCastException` issues.

Shouldn't `JsonObject.getArray` and `JsonObject.isArray` be completely `@Depricated` at this point? Or is there still a use case for those?

**Comment by jdereg** [comment]
I think you are correct, that we no longer need those APIs on JsonObject.  Here is the main change to be aware of (for the better): @items and @keys *only* show up when you have a Map with non-String keys.   In all cases, it is able to bypass using @items and @keys.  If you have a Map with some Object type as key, for example, those json-io will write the map out with @keys which will contain the object [{}, {}, ... ] keys, and the @items will contain the associated values.  Back to your point, even in this case, the isArray() and getArray() are still irrelevant.

**Comment by jdereg** [comment]
I will mark those APIs as @Depricated and ultimately remove them.

**Comment by rednoah** [comment]
Thanks for the help. I understand how it works now. :)
