### ISSUE TITLE
Provide a means of automatically reading an object with a custom reader

### ISSUE THREAD

**Issue by francisu** [jdereg/json-io#76]
Currently the custom reader mechanism does not allow you to automatically read the current object, it has to be done entirely manually.

The use case for this and https://github.com/jdereg/json-io/issues/75 is to be able to add a single field to the serialized output of certain objects (to track a version number), but otherwise read and write the object automatically and normally.

A pull request will be provided.

**Comment by jdereg** [comment]
thank you (@francisu) for the pull request that implements this.
