### ISSUE TITLE
FIELD_SPECIFIERS does not allow subclasses field to be serialized

### ISSUE THREAD

**Issue by sgandon** [jdereg/json-io#78]
Hello,
Here is the documentation for FIELD_SPECIFIER map option for serializing objects
`// Set value to a Map<Class, List<String>> which will be used to control which fields on a class are output`
So what I understand from this is that it will only specify the field for given class to be serialized but implicitly means that subclasses fields shall be serialized.
But this is not the case.
here is the test case that show the opposite.
```
    @Test
    void testExternalFieldSpecifierInheritance()
    {
        Map<Class, List<String>> fieldSpecifiers = [(PainfulToSerialize.class):['name']]
        MorePainfulToSerialize painful = new MorePainfulToSerialize()
        painful.name = "Android rocks"
        painful.age = 50;

        def args = [(JsonWriter.FIELD_SPECIFIERS):fieldSpecifiers]
        String json = JsonWriter.objectToJson(painful, args)
        Map check = (Map) JsonReader.jsonToJava(json, [(JsonReader.USE_MAPS):true] as Map)
        assertTrue(check.size() == 1)
        assertTrue(check.containsKey("name"))
```
here I would expect the MorePainfulToSerialize.age to be serialized because we only specified the *name* field for the parent class PainfulToSerialize.
So now if you specify a FIELD_SPECIFIERS for a given class, all fields that are added in subclasses will never be serialized which seems strange and make this feature not very useful I think.

**Comment by jdereg** [comment]
Closing the issue as both white-list and black-list support provides sufficient customization.
