### ISSUE TITLE
add a backlist of field not to be serialized

### ISSUE THREAD

**Issue by sgandon** [jdereg/json-io#79]
if we have an object that has fields not to be serialized in certain cases, which means we cannot use transient for this, there is not way to specify this.
I thought I could be using the FIELD_SPECIFIERS to specify  a white list of field thus removing the fields from this list but there is an issue with subclasses that does not allow this for subclasses ( see #78 ).
SO what would be great is to have a black list of field not be serialized.
I'll try to create a PR for this.

**Comment by jdereg** [comment]
Going through all pull requests / issues today / this weekend.  Should release a json-io 4.5.0 by Sunday.
