### ISSUE TITLE
Deserealize list of data

### ISSUE THREAD

**Issue by Senich** [jdereg/json-io#81]
Thanks for your lib, I use it in my everyday work extensively but I still cant figure out how to deserialize list of objects. Now I have to make a top level wrapper where I can put my list of objects and then I  deserialize this wrapper and get the data from it's field. But it seems a bit excessively. Is there better way to do this?
Something like
```
List<MyData> objectList;
String jsonString = JsonWriter.objectToJson(list);
```
and then
```
List<MyData> deserObjectList = JsonReader.jsonToJava(jsonString, MyData.class)
```

**Comment by jdereg** [comment]
Are you writing a list of disparate objects (forest rather than a tree)?.
If so, the only way to do that all at once is to put them in a List or
Object[] and serialize them as you have above.  The Object[] might make the
JSON a little prettier.

**Comment by Senich** [comment]
No, everything is simplier. All objects in a list are similar. 
It's a shame to admit, but after you answered I figured out how implement what I want.
```
List<Card> cards = ne.getSupportedCards();     
String jsonString = JsonWriter.objectToJson(cards);
List<Card> desCards = (List<Card>) JsonReader.jsonToJava(jsonString);
```
Just need to cast JsonReader output into List of objects (!) and everything works perfect.
Thank you!
