### ISSUE TITLE
Unclear error when failing to load a class sometimes

### ISSUE THREAD

**Issue by francisu** [jdereg/json-io#87]
We are working in an OSGi environment and in the case where a @type class cannot be loaded, a LinkedHashMap is created instead and then it gets an error when it tries to assign that object. This was difficult to debug. There should be a clear error indicating the type not found which would make this problem easier to track.

PR is coming to address this.

**Comment by jdereg** [comment]
thank you (@francisu) for the pull request that fixes this.
