### ISSUE TITLE
About performance

### ISSUE THREAD

**Issue by fabienrenaud** [jdereg/json-io#91]
I ran some benchmarks using JMH against a bunch of Java JSON libraries (jackson, gson, genson, org.json, etc.) and added json-io to my panel of tests and was very surprised (not to say chocked) about the performance of json-io.

The results are here: https://github.com/fabienrenaud/java-json-benchmark

json-io performs comparably to org.json...

I read the readme documentation of json-io and couldn't find any hints about how to boost performance nor couldn't find anything I could use to get better result (and I want to :) ).

Did I miss something?

As I was using json-io, I noticed that although capable of dealing with POJOS, it doesn't surface any factories. Maybe those are hidden internally... 

Did you try to profile (i guess with YourKit?) the project to see if there isn't some obvious bottlenecks that can easily be fixed?

**Comment by jdereg** [comment]
First of all, thank you very much for including json-io in your performance benchmark.  I was happy to see that it was on par with gson, however, based on some of the others' results, there is room for improvement.

In your tests, I would think you would serialize a simple JSON object as well as complex object graphs.  Would you elaborate on that?

For testing, here is what I would use:

**Writing...**
Map options = new HashMap();
options.put(JsonWriter.USE_MAPS, true);
String json = JsonWriter.objectToJson(axis, options);

**Reading...**
Object obj = JsonReader.jsonToJava(json)  // String or Stream input

There are lots of options on writing and reading.  For example, you can mark fields to be excluded from a particular class (black list or white list approach).  If you have a class that is not instantiating, you can assign an 'instantiator' class and associated it to the troubled class.  Your instantiator class will be called when any objects of that type are read in.

If you read the readme.md (main page) of json-io, you will see a lot of explanation about all the input options that can be supplied in the input maps to control and customize the operation of json-io.

I will get out YourKit and re-run it on json-io and see if I can't find any other areas for performance improvement - I just had it out recently, and was able to improve speed and reduce memory consumption on my n-cube project.

**Comment by fabienrenaud** [comment]
For reading, I use JsonReader.jsonToJava. [See here](https://github.com/fabienrenaud/java-json-benchmark/blob/master/src/main/java/com/github/fabienrenaud/jjb/StreamDeserialization.java#L108)
For writing, I do use JsonWriter.objectToJson. [See here](https://github.com/fabienrenaud/java-json-benchmark/blob/master/src/main/java/com/github/fabienrenaud/jjb/StreamSerialization.java#L114). The options are instantiated once on [JsonBase](https://github.com/fabienrenaud/java-json-benchmark/blob/master/src/main/java/com/github/fabienrenaud/jjb/JsonBase.java) and reuse over and over...

> In your tests, I would think you would serialize a simple JSON object as well as complex object graphs. Would you elaborate on that?

I serialize/deserialize [a fairly simple POJO](https://github.com/fabienrenaud/java-json-benchmark/tree/master/src/main/java/com/github/fabienrenaud/jjb/model) but complex enough to have deal with lists of primitive types and objects of variable size.
This is also the typical kind of payload I have come across when I had to work with json on some big production environment...

All tests in the benchmark deserialize/serialize the same objects so the comparisons are fair... unless json-io is very much geared against very complex graphs (any payload/model/schema of such i can use for testing is welcome)

> I was happy to see that it was on par with gson

For serialization, yes. Deserialization performance is closer to org.json though.

Happy to help and/or re-run the tests if you have any suggestions of new releases for json-io. You can also easily run the benchmark I wrote by simply running something like: `./bench deser --libs jsonio,jackson`.

**Comment by jdereg** [comment]
Fabien, I released json-io 4.5.0 yesterday.  This release improves the read speed.  I was hoping you could re-run your speed test with json-io 4.5.0 and update the comparison numbers.  In my testing, reading is about 50% faster than 4.4.0.  There were other functional enhancements listed in the readme as well (nothing that should affect how you use json-io for your tests).

**Comment by jdereg** [comment]
I hope to see some improvement in the reading speed in your graphs.

Separately, I forgot to mention that json-io can be used instead of ObjectInputStream / ObjectOutputStream.  It is a true object-graph serializer.  I am not sure how well the other JSON libraries do with complex object graphs.  Many of my test case graphs fail when I try some of the other JSON parses with them.  json-io handles more object-graphs than ObjectInputStream / ObjectOutputStream because it does not require the objects to inherit from Externalizable or Serializable.

**Comment by jdereg** [comment]
If you take the 'public static class ManyArrays implements Serializable' class from my TestArrays.groovy file - that's a good start.  I cannot get gson to write / read that.  json-io handles it fine.

My TestArrays, TestCollections, and TestMaps often choke other JSON serializers.

**Comment by fabienrenaud** [comment]
I updated the benchmark: https://github.com/fabienrenaud/java-json-benchmark

I refactored the project such as I can easily test other kinds of payloads (like ManyArrays) but I still need to do a bit of work to get that one tested nicely...

**Comment by jdereg** [comment]
In addition to raw performance, another important factor to judge JSON serialization libraries is on the number of dependencies the library has (json-io none).  In addition to highlighting what other libraries the JSON library may bring along with it, how large is the library itself?

**Comment by jdereg** [comment]
Of course, the other factor is the robustness of the library.  Can it handle all the gnarley object graphs that are thrown at it?  What if the objects being serialized contained List<Map<String, Object>> and such?  How well libraries handle the collections and combined collections is important.

**Comment by fabienrenaud** [comment]
The size of the library usually only matter for mobile clients. So not always relevant.
There is also the impact on memory and how well it would perform in a non HotSpot environment... but I am primarily measuring throughput performance for server-like environment (hotspot, large heap) for now.

All the json libraries I have in my benchmark have no external dependencies either (except json-smart which has 1).

WIth what I have tested so far (not published), jackson supports just fine and faster deserialzing and serializing large graphs or anything (like ManyArrays). But cyclical dependencies (like TestObject) need some special love (annotations, configuration) to be handled gracefully (that's probably why it was "choking" for you). Gson seemed to require further configuration to serialize/deserialize that object.
That's what i meant by "need to do a bit of work to get that one tested nicely"...

The main feature which is really missing from jsonio to me is automatic databinding for serializing and deserializing POJOs without embedding the java type in the payload. 
Embedding the "@type" property is not realistic to use in production environments. Take for example, an iOS+Objective-C app sending a json request to a server in java. The json should be automatically deserializable via databinding but iOS has no reason (and should not) to know the type of the java object to use on the server...
This is why my benchmark is only showing jsonio/stream throughput performance by the way, because I can not test jsonio's databind feature with the generic json payloads all the other frameworks work with.

**Comment by jdereg** [comment]
When most clients receive json-io's payload, they safely ignore the '@type' property if it is there.  They can still make updates to the JSON object graph and ship it back to the server.  The server running json-io reader will automatically inject these changes.  Also, '@type' is only output when it cannot be inferred.  And there is an option to turn if off it you do not want to see it at all.

Many of the json-io followers / users are running Android.  That seems to be its 'wheelhouse.'  I wrote the initial version back in 2007 and have kept it updated since then.  We are using it in a production environment at a Fortune 500 Insurance company where I work.  Because it has many other users, it has 'seen' its share of complex object graphs, which has really strengthened it's robustness.

I do have one more update that I am releasing this weekend, that should help read speed a little more.  I believe it will move json-io up at least one notch on the read side.

**Comment by keeldragger** [comment]
Null pointer sucks
